### ISSUE TITLE
Xamarin.Androidx.Migration 1.0.7 Crashes on build

### ISSUE THREAD

**Issue by inforithmics** [xamarin/XamarinAndroidXMigration#41]
I upgraded to Xamarin.Androidx.Migration 1.0.7 and the build crashes with following error

[error]C:\Users\[user]\.nuget\packages\xamarin.androidx.migration\1.0.7\buildTransitive\monoandroid90\Xamarin.AndroidX.Migration.targets(227,9): Error : Could not load file or assembly 'Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The system cannot find the file specified.
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies)
   at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute()

The reason is that Xamarin.Androidx.Migration.Core references Mono.Cecil 0.11.1.0 but Mono.Cecil 0.11.2.0 is distributed with the nuget package.

DotPeek Image of the Mono.Cecil and Xamarin.AndroidX.Migration.Core

![image](https://user-images.githubusercontent.com/2290863/92178978-0b1f2a00-ee44-11ea-946d-8735a7c6120c.png)

**Comment by bbcun** [comment]
I had the same issue problably because of this :
![image](https://user-images.githubusercontent.com/46867900/92250690-ae635400-eec3-11ea-9bf5-2f4374f745cc.png)
The dll packed in the migration package is not the same as the referenced one.
In my case I changed the android  compile target to Android 10 and the problem went away

**Comment by CNBoland** [comment]
I'm experiencing the same after upgrading 1.0.6.2 > 1.0.7

**Comment by angpysha** [comment]
You can use my package until it will be updated 
https://www.myget.org/feed/xamformsangpysha/package/nuget/Xamarin.AndroidX.Migration
https://www.myget.org/F/xamformsangpysha/api/v3/index.json
For me this package fixed build

**Comment by CNBoland** [comment]
@angpysha Thank you!

**Comment by AlyElHaddad** [comment]
@moljac [this commit](https://github.com/xamarin/AndroidX/commit/313370874decb7a10e8a63025b4441a5c3057473#annotation_409601270) seems to have caused trouble. Even your [build pipelines are failing](https://github.com/xamarin/AndroidX/runs/1080843620) because of it. Would you please take a look at this asap?

**Comment by angelru** [comment]
the same issue!

**Comment by inforithmics** [comment]
Works now with the newest AndroidX.Migration package

https://www.nuget.org/packages/Xamarin.AndroidX.Migration/1.0.7.1

**Comment by levelfivecoder** [comment]
> Works now with the newest AndroidX.Migration package
> 
> https://www.nuget.org/packages/Xamarin.AndroidX.Migration/1.0.7.1

The issue got fixed with the latest version
